// apps/open-standup-solid/src/routes/[standupId]/index.tsx
import {
  A,
  createRouteAction,
  createRouteData,
  useParams,
  useRouteData,
} from "solid-start";
import { StandupUpdate } from "~/shared/types";
import {
  QueryClient,
  dehydrate,
  useQueryClient,
  hydrate,
} from "@tanstack/solid-query";
import { For, Show, createMemo, onCleanup, onMount } from "solid-js";
import PersonStatus from "~/components/PersonStatus";
import { supabase } from "~/shared/supabase";
import {
  getStandupMeeting,
  getStandupUpdates,
  useStandupState,
} from "~/shared/useStandupState";
import { getRandomOrderValue } from "~/shared/getRandomOrderValue";

const advanceCurrentPerson = async function ({
  standupId,
  finishUpdate,
  queryClient,
}: {
  /** If true, mark the current update as complete. If false, move to the next person without marking as complete. */
  finishUpdate: boolean;
  standupId: string;
  queryClient: QueryClient;
}) {
  // hopefully when this function is called, updates are already loaded
  const updates = queryClient.getQueryData<{ data?: StandupUpdate[] }>([
    "standup-series",
    standupId,
    "updates",
  ]);
  if (updates?.data?.every((up) => up.duration !== null)) {
    return;
  }
  const sortedUpdates = [...(updates?.data ?? [])]?.sort(
    (a, b) => (a.order ?? a.id) - (b.order ?? b.id),
  );
  const updatingIndex = sortedUpdates.findIndex(
    (person) => person.started_at !== null && person.duration === null,
  );
  const updatingUpdate =
    updatingIndex >= 0 ? sortedUpdates[updatingIndex] : undefined;
  const nextAfterCurrent = sortedUpdates.find(
    (person, index) => index > updatingIndex && person.duration === null,
  );
  const firstNotDone = sortedUpdates.find((person) => person.duration === null);
  const nextUpdate = nextAfterCurrent ?? firstNotDone;
  const updatedCurrentUpdate = updatingUpdate
    ? [
        {
          started_at: null,
          meeting_id: +standupId,
          person_name: updatingUpdate.person_name,
          id: updatingUpdate.id,
          duration: finishUpdate
            ? Date.now() - new Date(updatingUpdate.started_at!).getTime()
            : null,
          updated_at: new Date().toISOString(),
        },
      ]
    : [];
  const updatedNextUpdate =
    nextUpdate && nextUpdate.id !== updatingUpdate?.id
      ? [
          {
            id: nextUpdate.id,
            meeting_id: +standupId,
            person_name: nextUpdate.person_name,
            started_at: new Date().toISOString(),
            duration: null,
            updated_at: new Date().toISOString(),
          },
        ]
      : [];
  if (updates?.data?.every((update) => !update.optimistic)) {
    queryClient.setQueryData<{
      data: StandupUpdate[];
    }>(["standup-series", standupId, "updates"], (oldData) => {
      return {
        ...oldData,
        data:
          oldData?.data.map((d) => {
            if (d.id === updatedCurrentUpdate[0]?.id) {
              return {
                ...updatedCurrentUpdate[0],
                optimistic: true,
                order: d.order,
              };
            } else if (d.id === updatedNextUpdate[0]?.id) {
              return {
                ...updatedNextUpdate[0],
                optimistic: true,
                order: d.order,
              };
            } else {
              return d;
            }
          }) ?? [],
      };
    });
    const removeOldUpdating = supabase
      .from("updates")
      .upsert([...updatedCurrentUpdate, ...updatedNextUpdate]);

    await removeOldUpdating;
  }
  return true;
};

const resetStandup = async function ({
  queryClient,
  standupId,
  randomizeOrder,
}: {
  queryClient: QueryClient;
  standupId: string;
  randomizeOrder: boolean;
}) {
  const existingUpdates = queryClient.getQueryData<{
    data: StandupUpdate[];
  }>(["standup-series", standupId, "updates"]);
  const updatedUpdates =
    existingUpdates?.data
      .filter((d) => d.meeting_id === +standupId)
      .map((update) => {
        return {
          ...update,
          order: randomizeOrder ? getRandomOrderValue() : update.id,
          duration: null,
          started_at: null,
        };
      }) ?? [];
  // optimisitic update in solid-query
  queryClient.setQueryData<{
    data: StandupUpdate[];
  }>(["standup-series", standupId, "updates"], (oldData) => {
    return {
      ...oldData,
      data:
        oldData?.data.map((d) => {
          const matchingUpdate = updatedUpdates.find((u) => u.id === d.id);
          return matchingUpdate ?? d;
        }) ?? [],
    };
  });
  // actual update in supabase
  const result = await supabase
    .from("updates")
    .upsert(updatedUpdates)
    .eq("meeting_id", standupId);

  return result;
};

function useReactiveStandupState() {
  const queryClient = useQueryClient();

  // subscribe to supabase changes and update the queryClient
  onMount(() => {
    const sub = supabase
      .channel("updates")
      .on<StandupUpdate>(
        "postgres_changes",
        { schema: "public", event: "UPDATE", table: "updates" },
        (supaChange) => {
          const updatedMeeting = String(supaChange.new.meeting_id);
          queryClient.setQueryData<{
            data: StandupUpdate[];
          }>(["standup-series", updatedMeeting, "updates"], (oldData) => {
            return {
              ...oldData,
              data:
                oldData?.data.map((d) => {
                  if (d.id === supaChange.new.id) {
                    return supaChange.new;
                  } else {
                    return d;
                  }
                }) ?? [],
            };
          });
        },
      )
      .subscribe();
    onCleanup(() => {
      sub.unsubscribe();
    });
  });
}

export function routeData() {
  const params = useParams();
  const standupId = params.standupId;
  const queryClient = new QueryClient();

  return createRouteData(async () => {
    await queryClient.prefetchQuery({
      queryKey: ["standup-series", standupId, "updates"],
      queryFn: () => getStandupUpdates({ standupId }),
    });
    await queryClient.prefetchQuery({
      queryKey: ["standup-series", standupId, "meeting"],
      queryFn: () => getStandupMeeting({ standupId }),
    });
    return dehydrate(queryClient);
  });
}

export default function StandupMeetingComponent() {
  const params = useParams();
  const dehydratedQueryState = useRouteData<typeof routeData>();

  const queryClient = useQueryClient();
  hydrate(queryClient, dehydratedQueryState());
  const seriesQuery = useStandupState(params.standupId);
  useReactiveStandupState();
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [_, { Form }] = createRouteAction(async (formData: FormData) => {
    if (formData.get("Next") !== null) {
      const result = await advanceCurrentPerson({
        finishUpdate: true,
        standupId: params.standupId,
        queryClient,
      });
      return result;
    }
    if (formData.get("Skip") !== null) {
      const result = await advanceCurrentPerson({
        finishUpdate: false,
        standupId: params.standupId,
        queryClient,
      });
      return result;
    }
    if (formData.get("Reset") !== null) {
      const randomizeOrder =
        seriesQuery.seriesState()?.randomizeOnStart ?? false;
      resetStandup({
        queryClient,
        standupId: params.standupId,
        randomizeOrder,
      });
    }
  });

  const sortedPeople = createMemo(
    () => {
      return seriesQuery
        .seriesState()
        ?.people.map((a) => ({ ...a }))
        .sort((a, b) => (a.order ?? a.id) - (b.order ?? b.id));
    },
    undefined,
    {
      equals: (a, b) => {
        return (
          a?.every((p, i) => {
            return (
              a !== undefined &&
              b !== undefined &&
              p.id === b[i].id &&
              p.name === b[i].name &&
              p.order === b[i].order
            );
          }) ?? false
        );
      },
    },
  );

  return (
    <div class="p-3">
      <Show when={params.standupId === "1"}>
        <h2 class="font-bold text-lg p-1">Welcome!</h2>
        <p>
          This is Open Standup. An app to help teams have quick and simple sync
          meetings.
        </p>
        <p>Play with the demo below, or make your own meeting</p>
        <div class="flex justify-center py-1">
          <A href={"/new"} class="btn btn-neutral w-1/2">
            Create new standup
          </A>
        </div>
        <details>
          <summary class="cursor-pointer">How does it work?</summary>
          <p>
            The name of the currently updating person is highlighted in blue.
            The name of anyone who has already done their update is highlighted
            in green.
          </p>

          <p>
            Anyone in the world who is viewing the demo at the same time will
            see the same state that you see. Try using the buttons to change
            which participant is currently updating.
          </p>
        </details>
      </Show>
      <div class="flex justify-center items-center gap-2 pb-1">
        <Show
          when={!seriesQuery?.isLoading()}
          fallback={
            <div class="animate-pulse flex w-1/5 h-4 bg-slate-200 rounded" />
          }
        >
          <h2 class="font-semibold text-lg">
            {seriesQuery?.seriesState()?.title}
          </h2>
        </Show>
        <A
          class="edit-button btn btn-sm btn-outline"
          href={`/${params.standupId}/edit`}
        >
          Edit
        </A>
      </div>
      <Show
        when={!seriesQuery?.isLoading()}
        fallback={
          <div>
            <div class="animate-pulse h-5 bg-slate-200 rounded m-1" />
            <div class="animate-pulse h-5 bg-slate-200 rounded m-1" />
            <div class="animate-pulse h-5 bg-slate-200 rounded m-1" />
            <div class="animate-pulse h-5 bg-slate-200 rounded m-1" />
            <div class="animate-pulse h-5 bg-slate-200 rounded m-1" />
            <div class="flex">
              <span class="inline animate-pulse w-1/2 h-10 bg-slate-200 rounded m-1" />
              <span class="inline animate-pulse w-1/2 h-10 bg-slate-200 rounded m-1" />
            </div>
          </div>
        }
      >
        <Form>
          <For each={sortedPeople()}>
            {(person) => {
              const thisPersonUpdate = () =>
                seriesQuery
                  ?.meetingState()
                  ?.updates?.find(
                    (update) => update.personId === person.id && update.done,
                  );
              const current = () =>
                person.id === seriesQuery?.meetingState().currentlyUpdating;
              const optimistic = () =>
                thisPersonUpdate()?.optimistic ||
                (current() && seriesQuery.meetingState().currentOptimistic);
              const isDone = () => thisPersonUpdate() !== undefined;
              return (
                <PersonStatus
                  name={person.name}
                  done={isDone()}
                  current={current()}
                  optimistic={optimistic()}
                />
              );
            }}
          </For>
          <div class="pt-3 flex gap-1">
            {seriesQuery?.meetingState().allDone ? (
              <>
                <div class="flex-grow">All Done!</div>
                <button class="btn btn-neutral flex-grow" name="Reset">
                  Reset
                </button>
              </>
            ) : (
              <>
                <button class="btn btn-neutral flex-grow" name="Next">
                  Next
                </button>
                <button class="btn flex-grow btn-outline" name="Skip">
                  Skip
                </button>
              </>
            )}
          </div>
        </Form>
      </Show>
    </div>
  );
}

// apps/open-standup-qwik/src/routes/[standupId]/index.tsx
import type { Signal } from "@builder.io/qwik";
import {
  component$,
  useComputed$,
  useSignal,
  useTask$,
  useVisibleTask$,
} from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { server$, Form } from "@builder.io/qwik-city";
import { routeLoader$ } from "@builder.io/qwik-city";
import { Link, useLocation, routeAction$ } from "@builder.io/qwik-city";
import { StandupFormComponent } from "~/components/standup-component/standup-form-component";
import type { StandupMeeting, StandupSeries } from "~/shared/types";
import { getSbClient } from "~/server-helpers/get-sb-client";
import { Introduction } from "~/components/introduction/introduction";

export const useStandupSeries = routeLoader$<StandupSeries>(
  async (requestEventLoader) => {
    const standupId = requestEventLoader.params["standupId"];
    const sbClient = await getSbClient(requestEventLoader);
    const updatePeopleReq = sbClient
      .from("updates")
      .select("*")
      .eq("meeting_id", standupId)
      .order("id", { ascending: true }) as unknown as {
      data: { person_name: string; id: number; meeting_id: number }[];
    };
    const meetingsReq = sbClient
      .from("meetings")
      .select("*")
      .eq("id", standupId)
      .single();
    const [people, meetings] = await Promise.all([
      updatePeopleReq,
      meetingsReq,
    ]);
    return {
      id: standupId,
      people:
        people.data?.map((p) => ({
          id: String(p.id),
          name: p.person_name,
          order: p.id,
        })) ?? [],
      randomizeOnStart: meetings.data?.randomize_order ?? false,
      title: meetings.data?.title ?? "Unknown Title",
    };
  },
);

export const getStandupMeeting = server$(async function () {
  const sbClient = await getSbClient(this);
  const standupId = this.params["standupId"];

  const updates = await sbClient
    .from("updates")
    .select("*")
    .eq("meeting_id", standupId)
    .order("id", { ascending: true });
  const updatedAt = updates.data?.reduce((soFar, newOne) => {
    return new Date(newOne.updated_at).getTime() > soFar
      ? new Date(newOne.updated_at).getTime()
      : soFar;
  }, 0);
  return {
    allDone: updates.data?.every((update) => (update.duration ?? 0) > 0),
    seriesId: "1",
    updates: updates.data?.map((update) => ({
      done: (update.duration ?? 0) > 0,
      personId: String(update.id),
    })),
    updateTime: updatedAt !== undefined ? new Date(updatedAt) : new Date(),
    currentlyUpdating: updates.data
      ? String(updates.data?.find((update) => update.started_at !== null)?.id)
      : undefined,
  } as StandupMeeting;
});
export const useStandupMeeting = routeLoader$<StandupMeeting>(async () => {
  return getStandupMeeting();
});

export const advanceCurrentPerson = server$(async function ({
  finishUpdate,
}: {
  finishUpdate: boolean;
}) {
  const standupId = this.params["standupId"];

  const sbClient = await getSbClient(this);
  const updates = await sbClient
    .from("updates")
    .select("*")
    .eq("meeting_id", standupId);
  if (updates.data?.every((up) => up.duration !== null)) {
    return;
  }
  const sortedUpdates = [...(updates.data ?? [])]?.sort((a, b) => a.id - b.id);
  const updatingIndex = sortedUpdates.findIndex(
    (person) => person.started_at !== null && person.duration === null,
  );
  const updatingUpdate =
    updatingIndex >= 0 ? sortedUpdates[updatingIndex] : undefined;
  const nextAfterCurrent = sortedUpdates.find(
    (person, index) => index > updatingIndex && person.duration === null,
  );
  const firstNotDone = sortedUpdates.find((person) => person.duration === null);
  const nextUpdate = nextAfterCurrent ?? firstNotDone;
  const updatedCurrentUpdate = updatingUpdate
    ? [
        {
          started_at: null,
          meeting_id: +standupId,
          person_name: updatingUpdate.person_name,
          id: updatingUpdate.id,
          duration: finishUpdate
            ? Date.now() - new Date(updatingUpdate.started_at!).getTime()
            : undefined,
        },
      ]
    : [];
  const updatedNextUpdate =
    nextUpdate && nextUpdate.id !== updatingUpdate?.id
      ? [
          {
            id: nextUpdate.id,
            meeting_id: +standupId,
            person_name: nextUpdate.person_name,
            started_at: new Date().toISOString(),
          },
        ]
      : [];
  const removeOldUpdating = sbClient
    .from("updates")
    .upsert([...updatedCurrentUpdate, ...updatedNextUpdate]);

  await removeOldUpdating;
  return true;
});

export const useStandupNext = routeAction$(
  async (formValue, requestEventAction) => {
    const standupId = requestEventAction.params["standupId"];

    if (formValue.Next !== undefined) {
      return advanceCurrentPerson({ finishUpdate: true });
    } else if (formValue.Skip !== undefined) {
      return advanceCurrentPerson({ finishUpdate: false });
    } else if (formValue.Reset !== undefined) {
      const sbClient = await getSbClient(requestEventAction);
      await sbClient
        .from("updates")
        .update({ duration: null, started_at: null })
        .eq("meeting_id", standupId);
    }
    return true;
  },
);

/** Gets updated meeting state every 2 seconds when the window is visible and focused. If the window is un-focused, updates every 20s. */
export const usePollingMeeting = () => {
  const loaderMeeting = useStandupMeeting();
  const meeting = useSignal(loaderMeeting.value);
  const lastUpdated = useSignal(new Date());
  useVisibleTask$(async ({ cleanup }) => {
    // allows us to stop polling when the component is unmounted
    let keepListening = true;
    cleanup(() => (keepListening = false));
    while (keepListening) {
      const dueForUnfocusedUpdate =
        new Date().getTime() - lastUpdated.value.getTime() > 20_000;
      if (
        document.visibilityState === "visible" &&
        (document.hasFocus() || dueForUnfocusedUpdate)
      ) {
        const newMeetingState = await getStandupMeeting();
        meeting.value = newMeetingState;
        lastUpdated.value = new Date();
      }
      await new Promise((resolve) => setTimeout(resolve, 2_000));
    }
  });
  const numValue = useComputed$(() => {
    // get the most updated value. the loader will be most up-to-date if this instance made a change.
    const loaderCountDate = new Date(loaderMeeting.value.updateTime ?? 0);
    const pollingCount = new Date(meeting.value.updateTime ?? 0);
    return loaderCountDate > pollingCount ? loaderMeeting.value : meeting.value;
  });
  return numValue;
};

export const useEagerMeetingState = (
  standupNextAction: ReturnType<typeof useStandupNext>,
  meetingState: Signal<StandupMeeting>,
) => {
  const submitTime = useSignal<Date | undefined>();
  useTask$(({ track }) => {
    track(() => standupNextAction.isRunning);
    if (standupNextAction.isRunning) {
      submitTime.value = new Date();
    } else {
      submitTime.value = undefined;
    }
  });

  /**
   * The meetingState with optimistic updates if an action is in-progress.
   * There is also logic to make sure it doesn't optimistically update
   * if the real data is newer than the start of the action (for example, from polling).
   */
  return useComputed$(() => {
    /** We don't want to use an eager state update if the meeting state is newer and might already have the updated value. */
    const submitNewerThanMeetingState =
      submitTime.value &&
      meetingState.value.updateTime.getTime() < submitTime.value?.getTime();

    const skipping = standupNextAction.formData?.get("Skip") !== null;
    const nexting = standupNextAction.formData?.get("Next") !== null;
    const reseting = standupNextAction.formData?.get("Reset") !== null;
    if ((skipping || nexting) && submitNewerThanMeetingState) {
      const sortedUpdates = [...(meetingState.value.updates ?? [])]?.sort(
        (a, b) => +a.personId - +b.personId,
      );

      const updatingIndex = sortedUpdates.findIndex(
        (person) => person.personId === meetingState.value.currentlyUpdating,
      );
      const updatingUpdate =
        updatingIndex >= 0 ? sortedUpdates[updatingIndex] : undefined;
      const nextAfterCurrent = sortedUpdates.find(
        (person, index) => index > updatingIndex && !person.done,
      );
      const firstNotDone = sortedUpdates.find((person) => !person.done);
      const nextUpdate = nextAfterCurrent ?? firstNotDone;
      const updates = meetingState.value.updates.map((up) =>
        nexting && up.personId === updatingUpdate?.personId
          ? { ...up, done: true }
          : up,
      );
      return {
        ...meetingState.value,
        updates,
        allDone: updates.every((up) => up.done === true),
        currentlyUpdating: nextUpdate?.personId,
      };
    }
    if (reseting && submitNewerThanMeetingState) {
      return {
        ...meetingState.value,
        updates: meetingState.value.updates.map((u) => ({ ...u, done: false })),
        allDone: false,
      };
    }
    return meetingState.value;
  });
};

export default component$(() => {
  const location = useLocation();
  const loaderSeriesState = useStandupSeries();
  const standupNextAction = useStandupNext();
  const serverMeetingState = usePollingMeeting();
  const meetingState = useEagerMeetingState(
    standupNextAction,
    serverMeetingState,
  );

  return (
    <div class="flex flex-col gap-1">
      {location.params.standupId === "1" ? <Introduction /> : undefined}
      <h2 class="font-bold text-lg text-center meeting-title flex justify-center items-center gap-2">
        <div>{loaderSeriesState.value.title}</div>
        <Link
          class="edit-button btn btn-sm btn-outline"
          href={`/${location.params.standupId}/edit`}
        >
          Edit
        </Link>
      </h2>
      <Form action={standupNextAction}>
        <StandupFormComponent
          seriesState={loaderSeriesState.value}
          standupState={meetingState.value}
        />
      </Form>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Open Standup",
  meta: [
    {
      name: "name",
      content: "description",
    },
  ],
};
