// apps/open-standup-qwik/src/routes/[standupId]/index.tsx
import type { Signal } from "@builder.io/qwik";
import {
  component$,
  useComputed$,
  useSignal,
  useTask$,
  useVisibleTask$,
} from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { server$, Form } from "@builder.io/qwik-city";
import { routeLoader$ } from "@builder.io/qwik-city";
import { Link, useLocation, routeAction$ } from "@builder.io/qwik-city";
import { StandupFormComponent } from "~/components/standup-component/standup-form-component";
import type { StandupMeeting, StandupSeries } from "~/shared/types";
import { getSbClient } from "~/server-helpers/get-sb-client";
import { Introduction } from "~/components/introduction/introduction";

export const useStandupSeries = routeLoader$<StandupSeries>(
  async (requestEventLoader) => {
    const standupId = requestEventLoader.params["standupId"];
    const sbClient = await getSbClient(requestEventLoader);
    const updatePeopleReq = sbClient
      .from("updates")
      .select("*")
      .eq("meeting_id", standupId)
      .order("id", { ascending: true }) as unknown as {
      data: { person_name: string; id: number; meeting_id: number }[];
    };
    const meetingsReq = sbClient
      .from("meetings")
      .select("*")
      .eq("id", standupId)
      .single();
    const [people, meetings] = await Promise.all([
      updatePeopleReq,
      meetingsReq,
    ]);
    return {
      id: standupId,
      people:
        people.data?.map((p) => ({
          id: String(p.id),
          name: p.person_name,
          order: p.id,
        })) ?? [],
      randomizeOnStart: meetings.data?.randomize_order ?? false,
      title: meetings.data?.title ?? "Unknown Title",
    };
  },
);

export const getStandupMeeting = server$(async function () {
  const sbClient = await getSbClient(this);
  const standupId = this.params["standupId"];

  const updates = await sbClient
    .from("updates")
    .select("*")
    .eq("meeting_id", standupId)
    .order("id", { ascending: true });
  const updatedAt = updates.data?.reduce((soFar, newOne) => {
    return new Date(newOne.updated_at).getTime() > soFar
      ? new Date(newOne.updated_at).getTime()
      : soFar;
  }, 0);
  return {
    allDone: updates.data?.every((update) => (update.duration ?? 0) > 0),
    seriesId: "1",
    updates: updates.data?.map((update) => ({
      done: (update.duration ?? 0) > 0,
      personId: String(update.id),
    })),
    updateTime: updatedAt !== undefined ? new Date(updatedAt) : new Date(),
    currentlyUpdating: updates.data
      ? String(updates.data?.find((update) => update.started_at !== null)?.id)
      : undefined,
  } as StandupMeeting;
});
export const useStandupMeeting = routeLoader$<StandupMeeting>(async () => {
  return getStandupMeeting();
});

export const advanceCurrentPerson = server$(async function ({
  finishUpdate,
}: {
  finishUpdate: boolean;
}) {
  const standupId = this.params["standupId"];

  const sbClient = await getSbClient(this);
  const updates = await sbClient
    .from("updates")
    .select("*")
    .eq("meeting_id", standupId);
  if (updates.data?.every((up) => up.duration !== null)) {
    return;
  }
  const sortedUpdates = [...(updates.data ?? [])]?.sort((a, b) => a.id - b.id);
  const updatingIndex = sortedUpdates.findIndex(
    (person) => person.started_at !== null && person.duration === null,
  );
  const updatingUpdate =
    updatingIndex >= 0 ? sortedUpdates[updatingIndex] : undefined;
  const nextAfterCurrent = sortedUpdates.find(
    (person, index) => index > updatingIndex && person.duration === null,
  );
  const firstNotDone = sortedUpdates.find((person) => person.duration === null);
  const nextUpdate = nextAfterCurrent ?? firstNotDone;
  const updatedCurrentUpdate = updatingUpdate
    ? [
        {
          started_at: null,
          meeting_id: +standupId,
          person_name: updatingUpdate.person_name,
          id: updatingUpdate.id,
          duration: finishUpdate
            ? Date.now() - new Date(updatingUpdate.started_at!).getTime()
            : undefined,
        },
      ]
    : [];
  const updatedNextUpdate =
    nextUpdate && nextUpdate.id !== updatingUpdate?.id
      ? [
          {
            id: nextUpdate.id,
            meeting_id: +standupId,
            person_name: nextUpdate.person_name,
            started_at: new Date().toISOString(),
          },
        ]
      : [];
  const removeOldUpdating = sbClient
    .from("updates")
    .upsert([...updatedCurrentUpdate, ...updatedNextUpdate]);

  await removeOldUpdating;
  return true;
});

export const useStandupNext = routeAction$(
  async (formValue, requestEventAction) => {
    const standupId = requestEventAction.params["standupId"];

    if (formValue.Next !== undefined) {
      return advanceCurrentPerson({ finishUpdate: true });
    } else if (formValue.Skip !== undefined) {
      return advanceCurrentPerson({ finishUpdate: false });
    } else if (formValue.Reset !== undefined) {
      const sbClient = await getSbClient(requestEventAction);
      await sbClient
        .from("updates")
        .update({ duration: null, started_at: null })
        .eq("meeting_id", standupId);
    }
    return true;
  },
);

/** Gets updated meeting state every 2 seconds when the window is visible and focused. If the window is un-focused, updates every 20s. */
export const usePollingMeeting = () => {
  const loaderMeeting = useStandupMeeting();
  const meeting = useSignal(loaderMeeting.value);
  const lastUpdated = useSignal(new Date());
  useVisibleTask$(async ({ cleanup }) => {
    // allows us to stop polling when the component is unmounted
    let keepListening = true;
    cleanup(() => (keepListening = false));
    while (keepListening) {
      const dueForUnfocusedUpdate =
        new Date().getTime() - lastUpdated.value.getTime() > 20_000;
      if (
        document.visibilityState === "visible" &&
        (document.hasFocus() || dueForUnfocusedUpdate)
      ) {
        const newMeetingState = await getStandupMeeting();
        meeting.value = newMeetingState;
        lastUpdated.value = new Date();
      }
      await new Promise((resolve) => setTimeout(resolve, 2_000));
    }
  });
  const numValue = useComputed$(() => {
    // get the most updated value. the loader will be most up-to-date if this instance made a change.
    const loaderCountDate = new Date(loaderMeeting.value.updateTime ?? 0);
    const pollingCount = new Date(meeting.value.updateTime ?? 0);
    return loaderCountDate > pollingCount ? loaderMeeting.value : meeting.value;
  });
  return numValue;
};

export const useEagerMeetingState = (
  standupNextAction: ReturnType<typeof useStandupNext>,
  meetingState: Signal<StandupMeeting>,
) => {
  const submitTime = useSignal<Date | undefined>();
  useTask$(({ track }) => {
    track(() => standupNextAction.isRunning);
    if (standupNextAction.isRunning) {
      submitTime.value = new Date();
    } else {
      submitTime.value = undefined;
    }
  });

  /**
   * The meetingState with optimistic updates if an action is in-progress.
   * There is also logic to make sure it doesn't optimistically update
   * if the real data is newer than the start of the action (for example, from polling).
   */
  return useComputed$(() => {
    /** We don't want to use an eager state update if the meeting state is newer and might already have the updated value. */
    const submitNewerThanMeetingState =
      submitTime.value &&
      meetingState.value.updateTime.getTime() < submitTime.value?.getTime();

    const skipping = standupNextAction.formData?.get("Skip") !== null;
    const nexting = standupNextAction.formData?.get("Next") !== null;
    const reseting = standupNextAction.formData?.get("Reset") !== null;
    if ((skipping || nexting) && submitNewerThanMeetingState) {
      const sortedUpdates = [...(meetingState.value.updates ?? [])]?.sort(
        (a, b) => +a.personId - +b.personId,
      );

      const updatingIndex = sortedUpdates.findIndex(
        (person) => person.personId === meetingState.value.currentlyUpdating,
      );
      const updatingUpdate =
        updatingIndex >= 0 ? sortedUpdates[updatingIndex] : undefined;
      const nextAfterCurrent = sortedUpdates.find(
        (person, index) => index > updatingIndex && !person.done,
      );
      const firstNotDone = sortedUpdates.find((person) => !person.done);
      const nextUpdate = nextAfterCurrent ?? firstNotDone;
      const updates = meetingState.value.updates.map((up) =>
        nexting && up.personId === updatingUpdate?.personId
          ? { ...up, done: true }
          : up,
      );
      return {
        ...meetingState.value,
        updates,
        allDone: updates.every((up) => up.done === true),
        currentlyUpdating: nextUpdate?.personId,
      };
    }
    if (reseting && submitNewerThanMeetingState) {
      return {
        ...meetingState.value,
        updates: meetingState.value.updates.map((u) => ({ ...u, done: false })),
        allDone: false,
      };
    }
    return meetingState.value;
  });
};

export default component$(() => {
  const location = useLocation();
  const loaderSeriesState = useStandupSeries();
  const standupNextAction = useStandupNext();
  const serverMeetingState = usePollingMeeting();
  const meetingState = useEagerMeetingState(
    standupNextAction,
    serverMeetingState,
  );

  return (
    <div class="flex flex-col gap-1">
      {location.params.standupId === "1" ? <Introduction /> : undefined}
      <h2 class="font-bold text-lg text-center meeting-title flex justify-center items-center gap-2">
        <div>{loaderSeriesState.value.title}</div>
        <Link
          class="edit-button btn btn-sm btn-outline"
          href={`/${location.params.standupId}/edit`}
        >
          Edit
        </Link>
      </h2>
      <Form action={standupNextAction}>
        <StandupFormComponent
          seriesState={loaderSeriesState.value}
          standupState={meetingState.value}
        />
      </Form>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Open Standup",
  meta: [
    {
      name: "name",
      content: "description",
    },
  ],
};

// apps/open-standup-solid/src/routes/[standupId].tsx
import { createRouteAction, useParams } from "solid-start";
import { createClient } from "@supabase/supabase-js";
import { Database } from "~/shared/db-types";
import { Person, StandupMeeting } from "~/shared/types";
import {
  QueryClient,
  createQueries,
  useQueryClient,
} from "@tanstack/solid-query";
import { For, Show, createMemo, onCleanup, onMount } from "solid-js";
import PersonStatus from "~/components/PersonStatus";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

type StandupUpdate = Database["public"]["Tables"]["updates"]["Row"] & {
  optimistic?: boolean;
};

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: { persistSession: false },
});

const advanceCurrentPerson = async function ({
  standupId,
  finishUpdate,
  queryClient,
}: {
  finishUpdate: boolean;
  standupId: string;
  queryClient: QueryClient;
}) {
  const sbClient = supabase;
  // hopefully when this function is called, updates are already loaded
  const updates = queryClient.getQueryData<{ data?: StandupUpdate[] }>([
    "standup-series",
    standupId,
    "updates",
  ]);
  if (updates?.data?.every((up) => up.duration !== null)) {
    return;
  }
  const sortedUpdates = [...(updates?.data ?? [])]?.sort((a, b) => a.id - b.id);
  const updatingIndex = sortedUpdates.findIndex(
    (person) => person.started_at !== null && person.duration === null,
  );
  const updatingUpdate =
    updatingIndex >= 0 ? sortedUpdates[updatingIndex] : undefined;
  const nextAfterCurrent = sortedUpdates.find(
    (person, index) => index > updatingIndex && person.duration === null,
  );
  const firstNotDone = sortedUpdates.find((person) => person.duration === null);
  const nextUpdate = nextAfterCurrent ?? firstNotDone;
  const updatedCurrentUpdate = updatingUpdate
    ? [
        {
          started_at: null,
          meeting_id: +standupId,
          person_name: updatingUpdate.person_name,
          id: updatingUpdate.id,
          duration: finishUpdate
            ? Date.now() - new Date(updatingUpdate.started_at!).getTime()
            : null,
          updated_at: new Date().toISOString(),
        },
      ]
    : [];
  const updatedNextUpdate =
    nextUpdate && nextUpdate.id !== updatingUpdate?.id
      ? [
          {
            id: nextUpdate.id,
            meeting_id: +standupId,
            person_name: nextUpdate.person_name,
            started_at: new Date().toISOString(),
            duration: null,
            updated_at: new Date().toISOString(),
          },
        ]
      : [];
  if (updates?.data?.every((update) => !update.optimistic)) {
    queryClient.setQueryData<{
      data: StandupUpdate[];
    }>(["standup-series", standupId, "updates"], (oldData) => {
      return {
        ...oldData,
        data:
          oldData?.data.map((d) => {
            if (d.id === updatedCurrentUpdate[0]?.id) {
              return { ...updatedCurrentUpdate[0], optimistic: true };
            } else if (d.id === updatedNextUpdate[0]?.id) {
              return { ...updatedNextUpdate[0], optimistic: true };
            } else {
              return d;
            }
          }) ?? [],
      };
    });
    const removeOldUpdating = sbClient
      .from("updates")
      .upsert([...updatedCurrentUpdate, ...updatedNextUpdate]);

    await removeOldUpdating;
  }
  return true;
};

const resetStandup = async function ({
  queryClient,
  standupId,
}: {
  queryClient: QueryClient;
  standupId: string;
}) {
  // optimisitic update in solid-query
  queryClient.setQueryData<{
    data: StandupUpdate[];
  }>(["standup-series", standupId, "updates"], (oldData) => {
    return {
      ...oldData,
      data:
        oldData?.data.map((d) => {
          return { ...d, duration: null, started_at: null };
        }) ?? [],
    };
  });
  // actual update in supabase
  const result = await supabase
    .from("updates")
    .update({ duration: null, started_at: null })
    .eq("meeting_id", standupId);

  return result;
};

export const hasPersonUpdated = (
  person: Person,
  updates: StandupMeeting["updates"],
) => {
  return updates.some((update) => update.personId === person.id && update.done);
};

/** fetches necessary data for a standup state and subscribes to updates */
function useStandupState(standupId: string) {
  const queryClient = useQueryClient();
  const queries = createQueries(() => ({
    queries: [
      {
        queryKey: ["standup-series", standupId, "updates"],
        queryFn: async () => {
          return await supabase
            .from("updates")
            .select("*")
            .eq("meeting_id", standupId)
            .order("id", { ascending: true });
        },
      },
      {
        queryKey: ["standup-series", standupId, "meeting"],
        queryFn: async () => {
          return await supabase
            .from("meetings")
            .select("*")
            .eq("id", standupId)
            .single();
        },
      },
    ],
  }));
  // subscribe to supabase changes and update the queryClient
  onMount(() => {
    const sub = supabase
      .channel("updates")
      .on<StandupUpdate>(
        "postgres_changes",
        { schema: "public", event: "UPDATE", table: "updates" },
        (supaChange) => {
          const updatedMeeting = String(supaChange.new.meeting_id);
          queryClient.setQueryData<{
            data: StandupUpdate[];
          }>(["standup-series", updatedMeeting, "updates"], (oldData) => {
            return {
              ...oldData,
              data:
                oldData?.data.map((d) => {
                  if (d.id === supaChange.new.id) {
                    return supaChange.new;
                  } else {
                    return d;
                  }
                }) ?? [],
            };
          });
        },
      )
      .subscribe();
    onCleanup(() => {
      sub.unsubscribe();
    });
  });
  const isLoading = createMemo(() =>
    queries.some((q) => q.isLoading || q.isFetching),
  );
  const isError = createMemo(() => queries.some((q) => q.isError));
  const updates = () => queries[0].data?.data;
  const fetchedSeries = () => queries[1].data?.data;
  const seriesState = createMemo(() => {
    return {
      id: standupId,
      people:
        updates()?.map((p) => ({
          id: String(p.id),
          name: p.person_name,
          order: p.id,
        })) ?? [],
      randomizeOnStart: fetchedSeries()?.randomize_order ?? false,
      title: fetchedSeries()?.title ?? "Unknown Title",
    };
  });
  const meetingState = createMemo(() => {
    const updatedAt = updates()?.reduce((soFar, newOne) => {
      return new Date(newOne.updated_at).getTime() > soFar
        ? new Date(newOne.updated_at).getTime()
        : soFar;
    }, 0);
    const currentUpdate: () => StandupUpdate | undefined = () =>
      updates()?.find((update) => update.started_at !== null);
    return {
      allDone: updates()?.every((update) => (update.duration ?? 0) > 0),
      seriesId: standupId,
      updates: updates()?.map((update: StandupUpdate) => ({
        done: (update.duration ?? 0) > 0,
        personId: String(update.id),
        optimistic: update.optimistic,
      })),
      updateTime: updatedAt !== undefined ? new Date(updatedAt) : new Date(),
      currentlyUpdating: updates() ? String(currentUpdate()?.id) : undefined,
      currentOptimistic: currentUpdate()?.optimistic,
    } as StandupMeeting;
  });
  return { isLoading, isError, seriesState, meetingState };
}
export default function StandupMeetingComponent() {
  const params = useParams();
  const queryClient = useQueryClient();
  const seriesQuery = useStandupState(params.standupId);
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [_, { Form }] = createRouteAction(async (formData: FormData) => {
    if (formData.get("Next") !== null) {
      const result = await advanceCurrentPerson({
        finishUpdate: true,
        standupId: params.standupId,
        queryClient,
      });
      return result;
    }
    if (formData.get("Skip") !== null) {
      const result = await advanceCurrentPerson({
        finishUpdate: false,
        standupId: params.standupId,
        queryClient,
      });
      return result;
    }
    if (formData.get("Reset") !== null) {
      resetStandup({ queryClient, standupId: params.standupId });
    }
  });
  const people = createMemo(() => {
    return seriesQuery?.seriesState().people.map((p) => {
      const thisPersonUpdate = seriesQuery
        ?.meetingState()
        ?.updates?.find((update) => update.personId === p.id && update.done);
      const current = p.id === seriesQuery?.meetingState().currentlyUpdating;
      return {
        updated: thisPersonUpdate !== undefined,
        current,
        optimistic:
          thisPersonUpdate?.optimistic ||
          (current && seriesQuery.meetingState().currentOptimistic),
        ...p,
      };
    });
  });

  return (
    <div class="p-3">
      <Show when={seriesQuery?.isLoading()}>
        <div>Loading...</div>
      </Show>
      <h2 class="text-lg">{seriesQuery?.seriesState().title}</h2>
      ID: {params.standupId}
      <Form>
        <For each={people()}>
          {(person) => {
            return (
              <PersonStatus
                name={person.name}
                done={person.updated}
                current={person.current}
                optimistic={person.optimistic}
              />
            );
          }}
        </For>
        <div class="pt-3 flex gap-1">
          {seriesQuery?.meetingState().allDone ? (
            <>
              <div class="flex-grow">All Done!</div>
              <button class="btn btn-neutral flex-grow" name="Reset">
                Reset
              </button>
            </>
          ) : (
            <>
              <button class="btn btn-neutral flex-grow" name="Next">
                Next
              </button>
              <button class="btn flex-grow btn-outline" name="Skip">
                Skip
              </button>
            </>
          )}
        </div>
      </Form>
    </div>
  );
}
