// apps/open-standup-qwik/src/routes/p2p/[standupId]/edit/index.tsx
import { component$, $ } from "@builder.io/qwik";
import { useLocation, useNavigate } from "@builder.io/qwik-city";
import {
  SeriesForm,
  StandupSeriesNoId,
} from "~/components/series-form/series-form";
import { useSyncedSeriesState } from "~/hooks/useSyncedSeriesState";

export default component$(() => {
  const location = useLocation();
  const seriesState = useSyncedSeriesState(location.params["standupId"]);
  const navigate = useNavigate();
  const onSubmit = $((submitted: StandupSeriesNoId) => {
    seriesState.people = submitted.people;
    seriesState.randomizeOnStart = submitted.randomizeOnStart;
    seriesState.title = submitted.title;
    navigate(`/p2p/${seriesState.id}`);
  });

  return (
    <div>
      {seriesState.title.length > 0 ? (
        <SeriesForm series={seriesState} onSubmit$={onSubmit} />
      ) : (
        <>
          <div>Loading...</div>
          <div>It's possible this standup does not exist.</div>
        </>
      )}
    </div>
  );
});

// apps/open-standup-solid-convex/src/routes/[standupId]/edit.tsx
import { useNavigate, useParams } from "@solidjs/router";
import { SeriesForm, StandupSeriesNoId } from "~/components/SeriesForm";
import { updateMeeting } from "~/shared/updateMeeting";
import { useStandupState, SeriesState } from "~/shared/useStandupState";
import { Show } from "solid-js";

function toFormSeries(series: SeriesState): StandupSeriesNoId {
  return {
    title: series.title,
    randomizeOnStart: series.randomizeOnStart,
    people: series.people.map((p) => ({
      id: p._id,
      name: p.name,
      order: p.order,
    })),
  };
}

export default function EditStandupMeetingComponent() {
  const params = useParams();
  const meetingId = params["standupId"];
  const standup = useStandupState(meetingId);
  const navigate = useNavigate();

  const handleSubmit = async (formData: StandupSeriesNoId) => {
    const id = await updateMeeting({ ...formData, id: meetingId });
    navigate(`/${id}`);
  };

  return (
    <Show when={standup.seriesState()} fallback={<div>Loading...</div>}>
      {(series) => (
        <SeriesForm
          onSubmit={handleSubmit}
          initialSeries={toFormSeries(series())}
        />
      )}
    </Show>
  );
}
